name: PR Validation

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check PR title
      uses: amannn/action-semantic-pull-request@v5
      with:
        types: 'feat,fix,docs,style,refactor,test,perf,ci,chore,build,wip'
        branches: 'main'
        
    - name: Check PR size
      uses: actions/github-script@v5
      with:
        script: |
          const pr = context.payload.pull_request
          const size = pr.changed_files
          if (size > 100) {
            core.setFailed(`PR has ${size} changed files. Please keep PRs under 100 files.`)
          }

    - name: Check PR description
      uses: actions/github-script@v5
      with:
        script: |
          const pr = context.payload.pull_request
          if (!pr.body || pr.body.trim().length < 10) {
            core.setFailed('Please provide a detailed PR description.')
          }
